import "./globals.css";

import AOSInit from "./components/ui/aos-init";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        <div className="mx-auto min-h-screen w-full max-w-5xl mt-5 md:mt-5">
          <AOSInit />
          {children}
        </div>
      </body>
    </html>
  );
}
